version: '3'

services:
  db:
    build: ./db
    image: kitchen2/db
    ports:
      - 15432:5432
    healthcheck:
      test: ["CMD", "su", "postgres", "-c", "echo 'select 1' | psql"]
      interval: 5s
      timeout: 5s
      retries: 30
  frontend:
    build: ./frontend
    image: kitchen2/frontend
    env_file: ./frontend/dev.env
    ports:
      - 8080:8080
    depends_on:
      - db
